export const YANGON_TOWNSHIPS = [
  "Ahlone",
  "Bahan",
  "Botahtaung",
  "Dagon",
  "Hlaing",
  "Kamayut",
  "Kyauktada",
  "Lanmadaw",
  "Latha",
  "Mayangone",
  "Mingalar Taung Nyunt",
  "Pabedan",
  "Pazundaung",
  "Sanchaung",
  "Tamwe",
  "Thingangyun",
  "Yankin",
] as const;
